### ISSUE TITLE
Add multi-level todo's

### ISSUE THREAD

**Issue by just-hms** [Coding-Brownies/todo#21]
- [ ] add a field named `tabs` inside `Task`
- [ ] add the `tab` and `shift+tab` key bindinds
- [ ] move the tasks accordingly
- [ ] set a `MaxTabs` variable

**Comment by ionfarima** [comment]
Are you sure about that ?
